CREATE TABLE IF NOT EXISTS pokemon_data (
  id INTEGER PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type_1 VARCHAR(50) NOT NULL,
  type_2 VARCHAR(50),
  total INTEGER NOT NULL,
  hp INTEGER NOT NULL,
  attack INTEGER NOT NULL,
  defense INTEGER NOT NULL,
  sp_atk INTEGER NOT NULL,
  sp_def INTEGER NOT NULL,
  speed INTEGER NOT NULL,
  generation INTEGER NOT NULL,
  legendary BOOLEAN NOT NULL
  );
